version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies"
      - pip3 install -r srv-server/requirements.txt
  build:
    commands:
      - echo "Building Docker Image"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now" 
