version: 0.2

phases:
  install:
    commands:
      - "wget https://releases.hashicorp.com/terraform/1.9.0-alpha20240404/terraform_1.9.0-alpha20240404_linux_amd64.zip"
      - unzip terraform_1.9.0-alpha20240404_linux_amd64.zip
      - sudo mv terraform /usr/local/bin
      - rm terraform_1.9.0-alpha20240404_linux_amd64.zip
    pre_build:
      commands:
        - terraform init

    build:
      commands:
        - terraform $TF_COMMAND -auto-approve

    post_build:
      commands:
        - echo "Nothing to do in the post_build for now" 
