version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    pre_build:
      commands:
        - echo "Installing dependencies"
        - pip install requirements.txt

    build:
      commands:
        - echo "Building Docker Image"
        - docker build . -t "$DOCKER_USERNAME/py-app-server"
        - docker push "$DOCKER_USERNAME/py-app-server"

    post_build:
      commands:
        - echo "Nothing to do in the post_build for now"
