name: py-app terraform workflow
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terraform.yaml"
      - "./"
      - "!**/README.md"
  pull_request:
    types: 
    - opened
    - synchronize
    - reopened
    paths:
      - ".github/workflows/terraform.yaml"
      - "./"
      - "!**/README.md"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set AWS credentials
        run:
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
      - name: Terraform - Fmt
        id: fmt
        run: terraform fmt -check -diff -recursive

      - name: Terraform - Init
        id: init
        run: terraform init -upgrade -reconfigure

      - name: Terraform - Validate
        id: validate
        run: terraform validate 

      - name: Terraform - Plan
        if: github.ref != 'refs/heads/main'
        id: plan
        run: terraform plan 

      - name: Terraform - Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
